#:schema node_modules/wrangler/config-schema.json
name = "camping-packliste-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "camping-checkliste"
database_id = "4858773e-e50d-4655-8bb3-5396c623ca2d"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "camping-checkliste"
database_id = "4858773e-e50d-4655-8bb3-5396c623ca2d"
