#:schema node_modules/wrangler/config-schema.json
name = "camping-checkliste"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# [[d1_databases]]
binding = "DB"
database_name = "camping-db"
database_id = "4858773e-e50d-4655-8bb3-5396c623ca2d"
